---
apiVersion: v1
kind: Service
metadata:
  name: xyz-project-nodeport-service
spec:
  selector:
    app: xyz-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
